#!/usr/bin/env node

/**
 * Google Drive OAuth Setup Script
 *
 * Uses @sowonai/nestjs-google-oauth-integration for OAuth authentication.
 *
 * Usage:
 *   node setup-auth.js [--credentials /path/to/credentials.json]
 *
 * Prerequisites:
 *   1. Create project at https://console.cloud.google.com/
 *   2. Enable Google Drive API
 *   3. Create OAuth 2.0 credentials (Desktop app recommended)
 *   4. Download credentials.json to this directory
 */

require('reflect-metadata');
const fs = require('fs');
const path = require('path');
const { GoogleOAuthService, NullTokenRepository } = require('@sowonai/nestjs-google-oauth-integration');

const SCOPES = [
  'https://www.googleapis.com/auth/drive',
];

async function main() {
  // Parse command line arguments
  const args = process.argv.slice(2);
  let credentialsPath = null;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--credentials' && args[i + 1]) {
      credentialsPath = args[i + 1];
      break;
    }
  }

  // Default to credentials.json in skill directory
  if (!credentialsPath) {
    credentialsPath = path.join(__dirname, 'credentials.json');
  }

  if (!fs.existsSync(credentialsPath)) {
    console.error('Error: credentials.json not found');
    console.error('');
    console.error('Usage: node setup-auth.js [--credentials /path/to/credentials.json]');
    console.error('');
    console.error('To get credentials.json:');
    console.error('  1. Go to https://console.cloud.google.com/');
    console.error('  2. Create or select a project');
    console.error('  3. Enable Google Drive API');
    console.error('  4. Create OAuth 2.0 credentials (Desktop app)');
    console.error('  5. Download the JSON file as credentials.json');
    process.exit(1);
  }

  console.log('');
  console.log('Google Drive OAuth Setup');
  console.log('='.repeat(60));
  console.log(`Using credentials: ${credentialsPath}`);
  console.log('');
  console.log('A browser window will open for Google authorization...');
  console.log('');

  try {
    // Use @sowonai/nestjs-google-oauth-integration
    const tokenRepository = new NullTokenRepository();
    const oauthService = new GoogleOAuthService(tokenRepository, {
      credentialsFilename: credentialsPath,
      scopes: SCOPES,
    });

    // Authenticate and get refresh token
    const { clientId, clientSecret, refreshToken } = await oauthService.authenticateForRefreshToken();

    if (!refreshToken) {
      console.error('');
      console.error('Warning: No refresh token received!');
      console.error('');
      console.error('This usually happens when the app was previously authorized.');
      console.error('To get a new refresh token:');
      console.error('  1. Go to https://myaccount.google.com/connections');
      console.error('  2. Find and remove this app');
      console.error('  3. Run this script again');
      process.exit(1);
    }

    // Generate .env content
    const envContent = `# Google Drive API Credentials
# Generated by setup-auth.js on ${new Date().toISOString()}
# Using @sowonai/nestjs-google-oauth-integration

DRIVE_CLIENT_ID=${clientId}
DRIVE_CLIENT_SECRET=${clientSecret}
DRIVE_REFRESH_TOKEN=${refreshToken}
`;

    // Save to .env file in skill directory
    const envPath = path.join(__dirname, '.env');
    fs.writeFileSync(envPath, envContent);

    console.log('Authorization successful!');
    console.log('');
    console.log('='.repeat(60));
    console.log('');
    console.log(`Credentials saved to: ${envPath}`);
    console.log('');
    console.log('You can now use the Drive skill:');
    console.log('  node list-files.js');
    console.log('  node search-files.js "keyword"');
    console.log('  node download-file.js <file-id>');
    console.log('');
    console.log('='.repeat(60));

  } catch (error) {
    console.error('Authentication failed:', error.message);
    process.exit(1);
  }
}

main();
